module.exports = {
    descriptors: [
        'Big',
        'Muddy',
        'Roaming',
        'Granite',
        'Spooky',
        'Hollow',
        'Wandering',
        'Whispering',
        'Babbling',
        'Breezy',
        'Rocky',
        'Happy',
        'Solemn',
        'Sacred',
        'Quiet',
        'Eerie',
        'Shady',
        'Tumbling',
        'Misty',
        'Dusty'
    ],
    elements: [
        'Deer',
        'Tree',
        'Leaf',
        'Elk',
        'Cat',
        'Pine',
        'Wood',
        'Sunset',
        'Rain',
        'Sunrise',
        'Rock',
        'Diamond',
        'Ruby',
        'Horn',
        'Bottle',
        'Glass',
        'Eye',
        'Hand',
        'Acorn',
        'Bush'
    ],
    places: [
        'Camp',
        'Horse Camp',
        'Village',
        'Park',
        'Meadows',
        'Campgrounds',
        'Trail',
        'Creek',
        'Ghost Town',
        'Canyon',
        'Pond',
        'Bay',
        'Sands',
        'Forest',
        'Bluffs',
        'Hollow',
        'Grove',
        'Pointe',
        'Bend',
        'Woods'
    ]
}